{
  "openapi": "3.0.0",
  "info": {
    "title": "Exchange API",
    "description": "Crypto Exchange API",
    "contact": {
      "name": "Tomas Kronvall",
      "email": "tomas.kronvall@goobit.se"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://api-test.bt.cx/exchange/v1",
      "description": "Test",
      "variables": {}
    },
    {
      "url": "https://api.bt.cx/exchange/v1",
      "description": "Production",
      "variables": {}
    }
  ],
  "paths": {
    "/data": {
      "get": {
        "tags": [
          "api"
        ],
        "summary": "exchange-data",
        "description": "Exchange client config data",
        "operationId": "exchange-data",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DataResponse"
                },
                "example": {
                  "config": {
                    "ageLimits": {
                      "block": 16,
                      "warn": 18
                    },
                    "buyLimit": 10000,
                    "rates": [
                      {
                        "from": "SEK",
                        "to": "BTC",
                        "toName": "Bitcoin",
                        "rate": 35159.1564,
                        "networkFee": 0.57528818067936
                      },
                      {
                        "from": "SEK",
                        "to": "ETH",
                        "toName": "Ether",
                        "rate": 1154.887548,
                        "networkFee": 0
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/rates": {
      "get": {
        "tags": [
          "api"
        ],
        "summary": "rates",
        "description": "Latest exchange rates",
        "operationId": "rates",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RatesResponse"
                  },
                  "description": "OK"
                },
                "example": [
                  {
                    "from": "SEK",
                    "to": "BTC",
                    "toName": "Bitcoin",
                    "rate": 35159.1564,
                    "networkFee": 0.57528818067936
                  },
                  {
                    "from": "SEK",
                    "to": "ETH",
                    "toName": "Ether",
                    "rate": 1154.887548,
                    "networkFee": 0
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/orders": {
      "post": {
        "tags": [
          "api"
        ],
        "summary": "place-order",
        "description": "Place new buy order",
        "operationId": "place-order",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PlaceOrderRequest"
              },
              "example": {
                "buyCurrency": "BTC",
                "cryptoAddress": "3CMCRgEm8HVz3DrWaCCid3vAANE42jcEv9",
                "networkFee": 2.59,
                "personNumber": "20001212-1471",
                "sellAmount": "123",
                "timestamp": "\"2020-01-27T06:33:54.044Z\""
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OrdersResponse"
                },
                "example": {
                  "action": "ok",
                  "uuid": "a7c99565-f175-4db8-ab48-4006a3d5ab52"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": [
          "api"
        ],
        "summary": "get-orders",
        "description": "Get orders for customer",
        "operationId": "get-orders",
        "parameters": [
          {
            "name": "personNumber",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "example": "20000101-0107"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OrdersResponse1"
                },
                "example": {
                  "action": "ok",
                  "data": [
                    {
                      "personNumber": "20001212-1471",
                      "sellAmount": "123.00",
                      "buyCurrency": "BTC",
                      "payNetworkFee": 2.59,
                      "cryptoAddress": "3CMCRgEm8HVz3DrWaCCid3vAANE42jcEv9",
                      "buyAmount": "0.00342471",
                      "sellCurrency": "SEK",
                      "paymentMethodName": "Swedbank",
                      "orderId": "local59",
                      "timestamp": "2020-10-06T16:46:47.741Z",
                      "uuid": "a7c99565-f175-4db8-ab48-4006a3d5ab52"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/orders/{uuid}": {
      "get": {
        "tags": [
          "api"
        ],
        "summary": "get-order",
        "description": "Get order",
        "operationId": "get-order",
        "parameters": [
          {
            "name": "uuid",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "a7c99565-f175-4db8-ab48-4006a3d5ab52"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OrdersResponse2"
                },
                "example": {
                  "action": "ok",
                  "data": {
                    "personNumber": "20001212-1471",
                    "sellAmount": "123.00",
                    "buyCurrency": "BTC",
                    "payNetworkFee": 2.59,
                    "cryptoAddress": "3CMCRgEm8HVz3DrWaCCid3vAANE42jcEv9",
                    "buyAmount": "0.00342471",
                    "sellCurrency": "SEK",
                    "paymentMethodName": "Swedbank",
                    "orderId": "local59",
                    "timestamp": "2020-10-06T16:46:47.741Z",
                    "uuid": "a7c99565-f175-4db8-ab48-4006a3d5ab52"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/addresses/{symbol}": {
      "post": {
        "tags": [
          "api"
        ],
        "summary": "generate-address",
        "description": "Generate address",
        "operationId": "generate-address",
        "parameters": [
          {
            "name": "symbol",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "BTC"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GenerateAddressRequest"
              },
              "example": {
                "encrypt": false
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddressesResponse"
                },
                "example": {
                  "action": "ok",
                  "address": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo",
                  "pkey": "Kyou6Tt2rVzJS6N45SdUo61cq7K6FPvAEm5nJBWYimK4bY19Mo6c"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/addresses/{symbol}/{address}": {
      "get": {
        "tags": [
          "api"
        ],
        "summary": "validate-address",
        "description": "Validate address",
        "operationId": "validate-address",
        "parameters": [
          {
            "name": "symbol",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "BTC"
            }
          },
          {
            "name": "address",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddressesResponse1"
                },
                "example": {
                  "action": "ok",
                  "symbol": "BTC",
                  "address": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo",
                  "valid": true
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/addresses/{symbol}/{address}/balance": {
      "get": {
        "tags": [
          "api"
        ],
        "summary": "get-balance",
        "description": "Get balance",
        "operationId": "get-balance",
        "parameters": [
          {
            "name": "symbol",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "BTC"
            }
          },
          {
            "name": "address",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddressesBalanceResponse"
                },
                "example": {
                  "action": "ok",
                  "address": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo",
                  "balance": 10000000
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "500": {
            "description": "Server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "title": "Error",
        "required": [
          "action",
          "code",
          "message"
        ],
        "type": "object",
        "properties": {
          "action": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "PlaceOrderRequest": {
        "title": "PlaceOrderRequest",
        "required": [
          "buyCurrency",
          "cryptoAddress",
          "networkFee",
          "personNumber",
          "sellAmount",
          "timestamp"
        ],
        "type": "object",
        "properties": {
          "buyCurrency": {
            "type": "string"
          },
          "cryptoAddress": {
            "type": "string"
          },
          "networkFee": {
            "type": "number"
          },
          "personNumber": {
            "type": "string"
          },
          "sellAmount": {
            "type": "string"
          },
          "timestamp": {
            "type": "string"
          }
        },
        "example": {
          "buyCurrency": "BTC",
          "cryptoAddress": "3CMCRgEm8HVz3DrWaCCid3vAANE42jcEv9",
          "networkFee": 2.59,
          "personNumber": "20001212-1471",
          "sellAmount": "1000",
          "timestamp": "\"2020-01-27T06:33:54.044Z\""
        }
      },
      "GenerateAddressRequest": {
        "title": "GenerateAddressRequest",
        "required": [
          "encrypt"
        ],
        "type": "object",
        "properties": {
          "encrypt": {
            "type": "boolean"
          }
        },
        "example": {
          "encrypt": false
        }
      },
      "AddressesBalanceResponse": {
        "title": "AddressesBalanceResponse",
        "required": [
          "action",
          "address",
          "balance"
        ],
        "type": "object",
        "properties": {
          "action": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "balance": {
            "type": "integer",
            "format": "int32"
          }
        },
        "example": {
          "action": "ok",
          "address": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo",
          "balance": 10000000
        }
      },
      "AddressesResponse": {
        "title": "AddressesResponse",
        "required": [
          "action",
          "address",
          "pkey"
        ],
        "type": "object",
        "properties": {
          "action": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "pkey": {
            "type": "string"
          }
        },
        "example": {
          "action": "ok",
          "address": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo",
          "pkey": "Kyou6Tt2rVzJS6N45SdUo61cq7K6FPvAEm5nJBWYimK4bY19Mo6c"
        }
      },
      "AddressesResponse1": {
        "title": "AddressesResponse1",
        "required": [
          "action",
          "symbol",
          "address",
          "valid"
        ],
        "type": "object",
        "properties": {
          "action": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "valid": {
            "type": "boolean"
          }
        },
        "example": {
          "action": "ok",
          "symbol": "BTC",
          "address": "1Be34XEEEiRbAp2cdRaRQ7Vs1DT86vwEAo",
          "valid": true
        }
      },
      "DataResponse": {
        "title": "DataResponse",
        "required": [
          "config"
        ],
        "type": "object",
        "properties": {
          "config": {
            "type": "object"
          }
        },
        "example": {
          "config": {
            "ageLimits": {
              "block": 16,
              "warn": 18
            },
            "buyLimit": 10000,
            "rates": [
              {
                "from": "SEK",
                "to": "BTC",
                "toName": "Bitcoin",
                "rate": 35159.1564,
                "networkFee": 0.57528818067936
              },
              {
                "from": "SEK",
                "to": "ETH",
                "toName": "Ether",
                "rate": 1154.887548,
                "networkFee": 0
              }
            ]
          }
        }
      },
      "OrdersResponse": {
        "title": "OrdersResponse",
        "required": [
          "action",
          "uuid"
        ],
        "type": "object",
        "properties": {
          "action": {
            "type": "string"
          },
          "uuid": {
            "type": "string"
          }
        },
        "example": {
          "action": "ok",
          "uuid": "a7c99565-f175-4db8-ab48-4006a3d5ab52"
        }
      },
      "OrdersResponse1": {
        "title": "OrdersResponse1",
        "required": [
          "action",
          "data"
        ],
        "type": "object",
        "properties": {
          "action": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object"
            },
            "description": ""
          }
        },
        "example": {
          "action": "ok",
          "data": [
            {
              "personNumber": "20001212-1471",
              "sellAmount": "123.00",
              "buyCurrency": "BTC",
              "payNetworkFee": 2.59,
              "cryptoAddress": "3CMCRgEm8HVz3DrWaCCid3vAANE42jcEv9",
              "buyAmount": "0.00342471",
              "sellCurrency": "SEK",
              "paymentMethodName": "Swedbank",
              "orderId": "local59",
              "timestamp": "2020-10-06T16:46:47.741Z",
              "uuid": "a7c99565-f175-4db8-ab48-4006a3d5ab52"
            }
          ]
        }
      },
      "OrdersResponse2": {
        "title": "OrdersResponse2",
        "required": [
          "action",
          "data"
        ],
        "type": "object",
        "properties": {
          "action": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "action": "ok",
          "data": {
            "personNumber": "20001212-1471",
            "sellAmount": "123.00",
            "buyCurrency": "BTC",
            "payNetworkFee": 2.59,
            "cryptoAddress": "3CMCRgEm8HVz3DrWaCCid3vAANE42jcEv9",
            "buyAmount": "0.00342471",
            "sellCurrency": "SEK",
            "paymentMethodName": "Swedbank",
            "orderId": "local59",
            "timestamp": "2020-10-06T16:46:47.741Z",
            "uuid": "a7c99565-f175-4db8-ab48-4006a3d5ab52"
          }
        }
      },
      "RatesResponse": {
        "title": "RatesResponse",
        "required": [
          "from",
          "to",
          "toName",
          "rate",
          "networkFee"
        ],
        "type": "object",
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          },
          "toName": {
            "type": "string"
          },
          "rate": {
            "type": "number"
          },
          "networkFee": {
            "type": "number"
          }
        },
        "example": {
          "from": "SEK",
          "to": "BTC",
          "toName": "Bitcoin",
          "rate": 35159.1564,
          "networkFee": 0.57528818067936
        }
      }
    },
    "securitySchemes": {
      "API-Key": {
        "type": "apiKey",
        "description": "",
        "name": "X-API-Key",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "API-Key": []
    }
  ],
  "tags": [
    {
      "name": "api"
    }
  ]
}